<?xml version="1.0" encoding="utf-8"?><Database Name="Halwa System" Class="HalwaDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-8S20ENO;Initial Catalog=&quot;Halwa System&quot;;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Halwa_SystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmpID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>